name: "YAPF Formatter"
description: "Runs YAPF code formatter for Python."
author: Diego Valenzuela Iturra

inputs:
  args: # id of input
    description: "yapf args"
    required: true
    default: . --verbose --parallel --recursive --in-place
  yapf_version:
    description: "yapf version"
    required: false
    default: "latest"

runs:
  using: "docker"
  image: "Dockerfile"

branding:
  icon: "check-circle"
  color: "gray-dark"
